### ISSUE TITLE
dataset image upload fails silently

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1815] opened 2024-04-22 12:22 UTC
UPDATED 29Apr2024.
This bug is not related to dataset status as first suspected, but infact its a silent error related to the length of the figure description!

When the figure description is above the allowed length (I think its ~100char?) and you try to upload an image, the system fails to save any of the changes made when you click save, but it doesn't give any warning or notificiation.

As a curator
I want to be notified when (and why) image update fails
So that I Can rectify the issue and try again

**Describe the bug**
Trying to add the thumbnail image to dataset 102522, the dataset status was set to "author reviewing" at the time, I added the new thumbnail image and clicked save. The page returned to the dataset-list instead of the dataset 102522 page, when I returned to the dataset 102522 admin page the image had not been saved.
I changed the dataset status to "Submitted" and tried again to upload the thumbnail image and it worked.

**Update**- actually it didn't ! It looked like it worked, but when i went back to that page later it wasn't there, so the "Successfully updated" notification was lying.

**To Reproduce**
1. Go to a dataset admin page e.g https://gigadb.org/adminDataset/update/id/2785
2. if the dataset status is set to "Author review"
3. try to upload a thumbnail image

**Expected behavior**
The thumbnail image should be updatable no matter what status the dataset is set to.

**Comment by alli83** [comment] 2024-08-28 23:35
@only1chunts is this issue still occurring? I'm unable to reproduce the error.

**Comment by rija** [comment] 2024-09-02 07:56
I think the issues reported here may have been fixed with PR #1916, this can explain why issue cannot be reproduced.
so I'm closing this issue

**Closed as completed by rija** 2024-09-02 07:56 UTC
Labels: bug, bug:Impact=low
