### ISSUE TITLE
Upload script mis-reporting failure when its actually worked

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1531] opened 2023-10-30 08:58 UTC
**Describe the bug**
the upload script on-screen output always says it Fails, even when it has actually worked.

**To Reproduce**
1. save a valid excel spreadsheet to beta
2. log onto beta 
3. run the upload script
4. watch the on-screen report, it ends with a message saying unable to upload the spreadsheet, even when it has successfully uploaded the details to the database

## screenshots
The on-screen display of running the script (point 4 above):
![upload-script-run-says-failed1](https://github.com/gigascience/gigadb-website/assets/6037145/3251c75c-f2e5-4ae0-bba1-90f3131a6e88)

The end of the java.log file showing success:
![upload-script-run-says-failed-but-log-shows-success](https://github.com/gigascience/gigadb-website/assets/6037145/8397f80a-e5bf-4969-acfe-1d3caa03823a)

The beta.gigadb.org page showing the dataset uploaded:
![upload-script-run-says-failed-but-data-admin-page-shows-success](https://github.com/gigascience/gigadb-website/assets/6037145/53ebfbe0-5bfd-431f-9e40-4a7fd045aaf8)

**Comment by kencho51** [comment] 2023-11-02 03:48
Hi @only1chunts,

Can you share me the spreadsheet file `GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls`?

**Comment by kencho51** [comment] 2023-11-07 04:11
Given this spreadsheet: [GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls](https://github.com/gigascience/gigadb-website/files/13275522/GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls)

I have tested it in the upstream staging environments:

```
% % ssh -i output/privkeys-18.166.89.134/lily lily@18.166.89.134
Activate the web console with: systemctl enable --now cockpit.socket

Last login: Wed Nov  8 03:12:14 2023 from 218.189.31.218
[lily@ip-10-99-0-147 ~]$ ls uploadDir/
GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls
[lily@ip-10-99-0-147 ~]$ ls -al uploadDir/
total 304
drwx------. 2 lily lily     71 Nov  8 03:09 .
drwx------. 4 lily lily     91 Nov  8 03:08 ..
-rw-r--r--. 1 lily lily 307712 Nov  8 03:09 GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls
[lily@ip-10-99-0-147 ~]$ 
[lily@ip-10-99-0-147 ~]$ ls uploadDir/
GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls
[lily@ip-10-99-0-147 ~]$ sudo /home/centos/datasetUpload.sh
DROP TRIGGER
DROP TRIGGER
DROP TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
Done.
[lily@ip-10-99-0-147 ~]$ ls uploadDir/
javac.log  java.log
[lily@ip-10-99-0-147 ~]$ tail uploadDir/java.log 
Insert True: insert into file_attributes select 674314, 538644, 993, 'S4', null where not exists ( select null from file_attributes where id = 674314 ); 
Insert false: insert into file_attributes select 674314, 538644, 993, 'S4', null where not exists ( select null from file_attributes where id = 674314 ); 
Insert True: insert into file_attributes select 674315, 538645, 993, 'S5', null where not exists ( select null from file_attributes where id = 674315 ); 
Insert false: insert into file_attributes select 674315, 538645, 993, 'S5', null where not exists ( select null from file_attributes where id = 674315 ); 
Insert True: insert into file_attributes select 674316, 538646, 572, 'MIT', null where not exists ( select null from file_attributes where id = 674316 ); 
Insert false: insert into file_attributes select 674316, 538646, 572, 'MIT', null where not exists ( select null from file_attributes where id = 674316 ); 
>>>>>>>About to exec sqlTemp...
execution time: 66
**End success: GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls
[][lily@ip-10-99-0-147 ~]$ ls
GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls  uploadDir
[lily@ip-10-99-0-147 ~]$ ls uploadDir/
javac.log  java.log
[lily@ip-10-99-0-147 ~]$ cp GigaDBUpload-103462-GIGA-D-23-00053-moths-test-upload.xls uploadDir/
[lily@ip-10-99-0-147 ~]$ sudo /home/centos/datasetUpload.sh
DROP TRIGGER
DROP TRIGGER
DROP TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
Spreadsheet cannot not be uploaded, please check the logs!
Done.
[lily@ip-10-99-0-147 ~]$ 
```
![image](https://github.com/gigascience/gigadb-website/assets/64770635/53bd3ef2-a09f-453e-b6e6-892bcbb30686)

**Comment by kencho51** [comment] 2023-11-08 04:37
Hi,

I could reproduce the error `"Spreadsheet cannot not be uploaded, please check the logs!"` from my staging and upstream staging envs.

The excel spreadsheet uploader can only ingest xls file, and the `datasetUpload.sh` will move everything in /home/$user/uploadDir to /home/centos/uploadDir.

When executing the `datasetUpload.sh` for the first time, supposedly there is only one xls file which will be moved to centos account for the spreadsheet ingestion, then `java.log` and `javac.log` will then be created and moved to /home/$user/uploadDir.

The problem is if a user want to execute the `datasetUpload.sh` again by putting xls file into /home/$user/uploadDir which with files `java.log` and `javac.log`, technically the xls file, java.log and javac.log will be moved to /home/centos/uploadDir together because that is how `datasetUpload.sh` implemented. Then the xls will be ingested and consumed by the excel spreadsheet uploader, but java.log and javac.log will be remained. That will trigger the following code block in the `datasetUpload.sh as `/home/centos/uploadDir` is not empty:
```
if [[ -n "$(ls -A /home/centos/uploadDir)" ]];then
    echo "Spreadsheet cannot not be uploaded, please check the logs!"
    mv /home/centos/uploadDir/* "$uploadDir/"
fi
```

So, this is not a major bug as this bug does not from the excel spreadsheet uploader itself.
But the `datasetUpload.sh` does need to be refactored, at the moment, if a user wants to use the `datasetUpload.sh`, just need to ensure that there is no other files inside `/home/$user/uploadDir` execept the xls file.

**Comment by only1chunts** [comment] 2023-11-08 09:03
Thanks for investigating Ken, I will adjust our guidelines to tell curators to ensure the `uploadDir` ONLY contains the intended target file before running the upload script.

**Closed as completed** 2023-11-09 07:34 UTC
Labels: Ken, bug:Impact=high, must-have-for-go-live
