### ISSUE TITLE
use of FTP via command line

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1905] opened 2024-05-30 10:16 UTC
## User story

>As a author (or reviewer)
>I want to be able to access the private file storage area using command line 
>So that I can move my files from my server to the files.gigadb.org server

## Acceptance criteria

>Given I have been assigned a userbox by GigaDB curators 
>When I need to copy my data files from my server to the GigaDB server 
>Then I am able to do so via a common command line tool such as "ftp"

## Additional Info
Historically we've used FTP but I guess as long as we can give instructions on what to do it doesn't really matter what the method is! 

Could rclone work? if so we just need a good set of instructions to provide to users.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment] 2024-05-31 07:34
Hi @only1chunts ,

regarding the immediate issue with FTP, you still haven't told us the computer environment (OS/software) people having problems are using.
Without that info, we cannot reproduce, test and advise on syntax if we don't know who has problem.

no-one in the dev team can run a command called "ftp" as that simply doesn't exist on Mac. 
So once we know what environment people have trouble with we will need to build the appropriate environment to reproduce, test and check appropriate syntax and/or modify our ftp server configuration it turns out its an issue on the server.

In the meantime, if users want a command line (CLI) solution (I'm assuming nobody has problem when using GUI tools like FileZilla), I recommend [ncftp](https://www.ncftp.com/download/) which exist on all environments, and we know it works as that's what we use for testing.

rclone when not used for interacting with object storage services (wasabi, Tencent, aws s3), it is just a wrapper on top of existing tool  like ftp or sftp or ftp.  So it won't solve the problem (and Sftp/ftps requires managing certificates files which will be added burden on you when you interact with users)

**Comment by only1chunts** [comment] 2024-06-11 10:25
I think most Linux users are familiar with bog standard ftp as a CLI:
```
$ ftp --help 

Transfers files to and from a computer running an FTP server service
(sometimes called a daemon). Ftp can be used interactively.

FTP [-v] [-d] [-i] [-n] [-g] [-s:filename] [-a] [-A] [-x:sendbuffer] [-r:recvbuffer] [-b:asyncbuffers] [-w:windowsize] [host]

  -v              Suppresses display of remote server responses.
  -n              Suppresses auto-login upon initial connection.
  -i              Turns off interactive prompting during multiple file
                  transfers.
  -d              Enables debugging.
  -g              Disables filename globbing (see GLOB command).
  -s:filename     Specifies a text file containing FTP commands; the
                  commands will automatically run after FTP starts.
  -a              Use any local interface when binding data connection.
  -A              login as anonymous.
  -x:send sockbuf Overrides the default SO_SNDBUF size of 8192.
  -r:recv sockbuf Overrides the default SO_RCVBUF size of 8192.
  -b:async count  Overrides the default async count of 3
  -w:windowsize   Overrides the default transfer buffer size of 65535.
  host            Specifies the host name or IP address of the remote
                  host to connect to.

Notes:
  - mget and mput commands take y/n/q for yes/no/quit.
  - Use Control-C to abort commands.
```

The way I use Linux is a-typical because I have to use an emulator on my Windows machine so perhaps thats my issue? and I dont have the specific details of the author that flaged this issue to us but they sent screen shots of the same commands working on the parrot server but not working on the files.gigadb.org in what looked like a unix based environment.
![image](https://github.com/gigascience/gigadb-website/assets/6037145/a22f47bb-45b4-42e4-a7a4-fd8a04f92443)
![image](https://github.com/gigascience/gigadb-website/assets/6037145/07f0550d-b30c-4721-b447-91a36b6af831)



For me personally, I'm using Windows Poweshell on:
Windows 10 pro
version 22H2
OS build 19045.4412

and today it sort of worked, a bit... it did at least let me log in, but not perform a simple "ls" of the files:

```
PS C:\Users\Admin> ftp files.gigadb.org
Connected to files.gigadb.org.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 5 allowed.
220-Local time is now 09:59. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
200 OK, UTF-8 enabled
User (files.gigadb.org:(none)): user1
331 User user1 OK. Password required
Password:
230 OK. Current directory is /
ftp> ls
200 PORT command successful
425 Could not open data connection to port 59756: Connection timed out
ftp>
```

maybe the time-out might be indicative of the issue?

NB - ncftp doesn't appear to work in Windows powershell (despite what their website says, I cant get it to work!)

**Comment by rija** [comment] 2024-12-23 09:34
Closing, as unsure what's wrong. potentially we can reopen it after FUW if issue arises again

**Closed as completed by rija** 2024-12-23 09:34 UTC
Labels: backlog:Story, bug:Impact=high
