### ISSUE TITLE
mockup link is lost when changing the dataset status

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1816] opened 2024-04-22 12:26 UTC
**Describe the bug**
When the dataset status is changed from certain things to other things then the open the mockup URL button is lost, requiring you to create a new mockup URL.

**To Reproduce**
1. Go to a dataset admin page, e.g. https://gigadb.org/adminDataset/update/id/2785
2. If the dataset status is "Author review" and there is already a view mockup link button
3. then change the dataset status nack to "Submitted"
4. See the "view mockup url" button disappear

**Expected behavior**
Once a mokcup URL has been created there should not be any time when it is removed UNLESS someone actively clicks the re-generate mockup URL button.

**Comment by rija** [comment] 2024-04-22 16:19
Hi @only1chunts,

The root cause of the problem is the same as in #1817.
<img width="1359" alt="Screenshot 2024-04-22 at 6 17 22 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/b525ac0a-181c-4333-b7c3-3fc94631e960">

When the dataset is set to "ImportFromEM", you can see both links (the one to create/reset URLs, and the ones that open the just created mockup URLS):

**Comment by only1chunts** [comment] 2024-04-22 16:28
not sure your screenshot is showing a "problem"? That screenshot looks correct, i.e. the "create/reset private URL" and "open private URL" buttons should always be present (until the status is published)

**Comment by rija** [comment] 2024-05-07 20:48
Fixed in PR #1847

**Closed as completed by rija** 2024-05-07 20:48 UTC
Labels: bug, bug:Impact=low
