### ISSUE TITLE
add project image to GigaDB

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2148] opened 2024-12-23 10:45 UTC
## User story

>As a curator  
>I want to be able to add project information (including an image) to GigaDB and have it display nicely
>So that I can add datasets to project pages

## Acceptance criteria

>Given a dataset is part of a larger international project (e.g. the 1000 genomes project)
>When I want to create a link to that project
>Then I can add the project name to GigaDB
>And the project URL to GigaDB
>And a suitable thumbnail Image of the project to GigaDB

https://gigadb.org/adminProject/create

> Given a project exists in GigaDB
>And its linked to a dataset
>When I view that dataset page
>Then the project link is displayed with its appropriate thumbnail image

## Additional Info
We are already able to add the project information, however the "image" part if the problem, it asks for an image location, but when we use a URL for a public website it doesn't work properly, so what we need is a image upload box to be able to add the image in the same way we do for Dataset Thumbnail images (see ticket #325 )

![project_thumbnail_issue](https://github.com/user-attachments/assets/a1c0f95b-5afa-4091-b1b2-14c3d37cab8f)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment] 2024-12-30 09:50
Closing as this is a duplicate of #376

**Closed as completed by rija** 2024-12-30 09:50 UTC
Labels: backlog:Story
