### ISSUE TITLE
The Geolocation (altitude and longitude) of dataset in the sample attribute table is not standardized

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#2022] opened 2024-09-02 08:36 UTC
Relate to #1944

When I executed the query in the `actionMapbrowse` in my staging database,
```
SELECT d.identifier,  d.title, satt.value, sp.scientific_name as sciname, s.id as sampleid FROM dataset as d
INNER JOIN dataset_sample as dsam on dsam.dataset_id = d.id
INNER JOIN sample as s on s.id = dsam.sample_id
INNER JOIN sample_attribute as satt on satt.sample_id=s.id
INNER JOIN species as sp on sp.id = s.species_id
where satt.attribute_id = 269 and d.upload_status='Published' order by sampleid;
```

the returned `value` are something like, `not recorded`, `00Ã‚Â°15' N 98Ã‚Â°08' E`, `off Heligoland, North Sea` or `31.48`. 

I then further looked into the sample_attribute table using:
```
SELECT attribute_id, value, count(*) FROM sample_attribute WHERE attribute_id = 269 GROUP BY attribute_id, value order by count desc;
```

And then got this returns:
```
attribute_id value count
269	not provided	3473
269	restricted access	1096
269	not recorded	257
269	not collected	131
269	32Â°35'N 103Â°37'E	74
269	30Â°0'N 103Â°02'E	38
269	31Â°04â€²37â€³N, 121Â°10â€²35â€³E	29
269	Multiple	27
269	Not Recorded	22
269	29Â°02'N 100Â°17'E	19
269	30Â°34'N 104Â°03'E	19
269	35Â°24'N 116Â°34'E	19
269	29Â°24'N 105Â°36'E	18
269	19Â°07â€²16â€³N, 109Â°05â€²00â€³E	11
269	42Â°20' N, 126Â°50' E	11
269	not applicable	10
269	31.48	9
269	N31Â°, E117Â°	9
269	35.9940Â° N, 78.8986Â° W	8
269	Aldabra, Indian Ocean	5
269	Sri Lanka, Indian Ocean	4
269	off Heligoland, North Sea	4
269	Morro Bay, San Luis Obispo, California, USA, Pacific Ocean	3
269	02Ã‚Â°50'56'' N 95Ã‚Â°56'24'' E	3
269	19Â°00â€²07â€³N, 109Â°32â€²33â€³E	3
269	Costa Brava, Spain, Mediterranean Sea	3
269	Kobe, Japan, Pacific Ocean	3
269	62Â°14'S, 58Â°47'W	3
269	29Â°24â€²00â€³N, 110Â°09â€²56â€³E	3
269	nor recorded	3
269	24Â°04â€²34â€³N, 110Â°08â€²17â€³E	3
269	Loblolly Bay, Anegada, British Virgin Islands, Caribbean Sea	2
269	00Ã‚Â°15' N 98Ã‚Â°07' E	2
269	00Ã‚Â°02' S 73Ã‚Â°24' E	2
269	23Â°20â€²22â€³N, 108Â°22â€²49â€³E	2
269	Weddell Sea, Southern Ocean	2
269	Caribbean Sea	2
269	Iceland Basin, Atlantic Ocean	2
269	37Â°26'N, 126Â°22'E	2
269	Atapupu, Timor, Indonesia, Indian Ocean	2
269	Singapore, Pacific Ocean	2
269	30.50′–30.180′N, 114.210′–114.390′E	2
269	Arendal, Norway, Skagerrak, North Sea	2
269	33Ã‚Â°35'20'' N 135Ã‚Â°10'50'' E	2
269	East Asia, Pacific Ocean	2
269	21Â°54â€²3â€³N, 111Â°23â€²58â€³E	2
269	13894; 19Â°33â€™3â€�N, 110Â°47â€™25â€� E	2
269	S off New Scotia, Atlantic Ocean	2
269	New Caledonia, Pacific Ocean	2
269	Bassin de la Gazelle, Kerguelen Islands, Southern Ocean	2
269	00Ã‚Â°15' N 98Ã‚Â°08' E	2
269	Gauss Base, Antarctica, Southern Ocean	2
269	18Â°59â€²58â€³N, 109Â°05â€²03â€³E	2
269	North Sea	2
269	off Florida, USA, Gulf of Mexico	2
269	not available	2
269	Penguin Bank, Oahu Island, Hawaii, USA, Pacific Ocean	2
269	35.202773	1
269	off Elephant Island, Southern Ocean	1
269	Monrovia, Liberia	1
269	24Â°58â€²12â€³N, 112Â°53â€²17â€³E	1
269	35.114876	1
269	23Â°36â€²21â€³N, 113Â°57â€²18â€³E	1
269	Abeloya, Kong Karls Land	1
269	Not recorded	1
269	30Â°36â€²28â€³N, 119Â°52â€²22â€³E	1
269	Romblon, Philippines, Pacific Ocean	1
269	Hastings, Barbados, Caribbean Sea	1
269	Dry Tortugas, Florida, USA, Gulf of Mexico	1
269	29Â°37â€²51â€³N, 109Â°50â€²17â€³E	1
269	Rovinj, Croatia, Mediterranean Sea	1
269	26Â°47â€²29â€³N, 117Â°02â€²21â€³E	1
269	Polana Beach, Mozambique, Indian Ocean	1
269	21Â°50â€²13â€³N, 108Â°03â€²27â€³E	1
269	Madeira, Portugal, Atlantic Ocean	1
269	Misaki, Japan, Pacific Ocean	1
269	Parry Island, Eniwetok Atoll, Marshall Islands, Pacific Ocean	1
269	18Â°54â€²40â€³N, 109Â°41â€²12â€³E	1
269	25Ã‚Â°40'00'' S 86Ã‚Â°46'05'' W	1
269	23Â°10â€²47â€³N, 113Â°21â€²33â€³E	1
269	18Â°39â€²43â€³N, 110Â°16â€²19â€³E	1
269	Pemba Channel, Tanzania, Indian Ocean	1
269	33Ã‚Â°56' N 26Ã‚Â°43' E	1
269	Port Jackson, Sydney, Australia, Pacific Ocean	1
269	Mombasa, Kenya, Indian Ocean	1
269	30Â°11â€²36â€³N, 118Â°09â€²20â€³E	1
269	35Ã‚Â°10' S 23Ã‚Â°02' E	1
269	Low Island, Low Isles, Australia, Pacific Ocean	1
269	01Ã‚Â°49' N 45Ã‚Â°29' E	1
269	Ecuador, Pacific Ocean	1
269	Ralum, East New Britain, Papua New Guinea, Pacific Ocean,	1
269	60Â° 9â€² 0â€³ N, 24Â° 39â€² 30â€³ E	1
269	Maroon Point, Mauritius, Indian Ocean	1
269	40Ã‚Â°0Ã‚Â´38.02Ã‚Â´'N3Ã‚Â°52Ã‚Â´41.4Ã‚Â´Ã‚Â´E	1
269	Paita, Peru, Pacific Ocean	1
269	St. Thomas, Caribbean Sea	1
269	22Â°26â€²46â€³N, 106Â°53â€²17â€³E	1
269	61Ã‚Â°42' N 09Ã‚Â°36' W	1
269	35.161870	1
269	29Â°46â€²34â€³N, 110Â°05â€²50â€³E	1
269	Golf of Suez, Red Sea, Indian Ocean	1
269	31Ã‚Â°58'82'' S 174Ã‚Â°15'87'' E	1
269	29Â°33â€²33â€³N, 103Â°18â€²45â€³E	1
269	Azores, Portugal, Atlantic Ocean	1
269	43Ã‚Â°56' S 60Ã‚Â°52' W	1
269	Papua New Guinea, Pacific Ocean	1
269	45.5Â° N, 122.7Â° W	1
269		1
269	06Ã‚Â°19' S 12Ã‚Â°02' E	1
269	18Â°45â€²15â€³N, 110Â°12â€²43â€³E	1
269	35.192253	1
269	Angra Pequena, LÃƒÂ¼deritz, Namibia, Atlantic Ocean	1
269	34.0689Â° N, 118.4452Â° W	1
269	Jakarta, Indonesia, Pacific Ocean	1
269	30Ã‚Â°02'09'' N 28Ã‚Â°24'02'' W	1
269	S Chile, Pacific Ocean	1
```

So clearly, besides the CSP problem, the `value` itself in the `sample_attribute` table is not standardized and not formatted well, it causes the `geojson_features` array is empty,  which leads to no `dots` can be seen in the map in the `/site/mapbrowse` page. 

The sanity check in the `mapbrowse.php` is not enough to check all the `value` cases in the `sample_attribute` table in the current production database.

To do:

- [ ] Standardize the input value format, eg. only numerical is allowed
- [ ] Validation before the form saving
- [ ] Auto covert the existing values to numeric?

**Comment by rija** [comment] 2024-09-13 12:54
To ensure the relevant information stay together, here are the gitter chat converstion adding precision to this ticket:


The ticket of concern is [#2022](https://github.com/gigascience/gigadb-website/issues/2022), not #1944. The #1944's purpose is now only about fixing the CSP issue which I believed Ken  is finalising a PR for.

When you deploy GigaDB to AWS, the RDS PostgreSQL there get loaded with a backup of live data
You can make the following SQL query (from #2022 which also show the result) using pgAdmin/DBeaver/PHPStorm to get data that feeds into `mapbrowse.php`:

```
SELECT attribute_id, value, count(*) FROM sample_attribute WHERE attribute_id = 269 GROUP BY attribute_id, value order by count desc;
```

269 is the ID for `geographic location (latitude and longitude)` in the attribute table.
Clearly most, if not all of the results are invalid coordinates.

There is another query you can make:

```
SELECT attribute_id, value, count(*) FROM sample_attribute WHERE attribute_id = 270 GROUP BY attribute_id, value order by count desc;
```

Where 270 is the ID for `geographic location (country and/or sea,region)`

So there are cases in the results where the author seemed to have used the wrong attribute and put info in 269 instead 270.
There are  also cases of incorrect annotation to describe geolocation (that includes with weird characters too)
Finally there are the cases where the author cannot input the geolocation data and instead fills in the reason.

The curation guidelines in https://gigadb.org/site/guide (look for the aforementioned attributes labels in the "Required metadata" section)
Is very clear about what the annotation should be

Resolving [#2022](https://github.com/gigascience/gigadb-website/issues/2022) seems to be about:

1. data correction

- incorrect annotation should  be converted to the WGS84 system
- sample\_attributes whose values are country or see, region, should have their attribute\_id changed from 269 to 270
- sample\_attributes where `geographic location (latitude and longitude)` contains reasons should probably be removed

2. Code change

- validation on admin sample controller create/update
- message on an admin sample view for sample with attribute for `geographic location (latitude and longitude)` with invalid content
- cleanup mapbrowse.php

**Comment by rija** [comment] 2024-09-13 12:56
Hi @alli83,

After talking to @only1chunts, I can confirm the button on the page that calls the sample map should be seen by everyone, not just logged-in user.

**Comment by only1chunts** [comment] 2024-09-13 13:17
Hi, Not been following this as closely as I should have been, but please do NOT use attribute 269, that is an old obsolete attributes that are no longer being actively used and eventually the curation team will convert those to the individual attributes for latitude (391) and longitude (392). The individual lat and lon terms are the ones that should be mapped as per the request in ticket #831.

**Comment by rija** [comment] 2024-09-13 13:32
Hi @alli83,

It seems that we were looking at the wrong attributes IDs.
Making the work described in this ticket redundant.

The work to be done to get mapbrowse working again is to update the script to read latitude and longitude from different attribute values. That work is already described in #831 which is the one to work on, so I'm closing this one

**Closed as completed by rija** 2024-09-13 13:32 UTC
Labels: bug
