### ISSUE TITLE
Replace Unicode Character

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#276] opened 2019-01-28 10:03 UTC
To ensure that README files display properly, we need to make the following changes to the TITLE and the DESCRIPTION in GigaDB.

1. Replace Unicode Character LEFT SINGLE QUOTATION MARK [‘] with APOSTROPHE [']

2. Replace Unicode Character RIGHT SINGLE QUOTATION MARK [’] with APOSTROPHE [']

Example: To see an example of APOSTROPHE ['] displaying correctly find the word [insect's] at the following URL:

ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100560/readme_100560.txt

**Comment by jessesiu** [comment] 2019-10-14 02:41
Do you mean replace those characters in the database title and description?

**Comment by kencho51** [comment] 2020-08-12 03:49
@ChrisArmit Would you please further clarify your request, like which `TITLE` and `DESCRIPTION`?

**Comment by only1chunts** [comment] 2020-08-12 10:09
Hi @kencho51 , 
This is a generic issue that may or may-not be be present in multiple datasets, so it will require a search to find and replace. 
The issue can be illustrated by the attached readme file that I just generated from a test [dataset](http://gigadb.org/dataset/view/id/200051/token/S7iZ8uzhes9NCHgF). The webpage presents the left and right quotation marks absolutely fine, the issue is how these are displayed in the plain text readme files that we generate from the database , the attached file was generated from the above dataset using the usual script and it shows the issue with the quotation marks.
[readme_200051.txt](https://github.com/gigascience/gigadb-website/files/5061982/readme_200051.txt)

There are similar issues with certain other non-ascii text, it would be good to identify those and ensure they are correctly represented.
Hope that helps clarify?

**Comment by pli888** [comment] 2020-08-14 04:44
@only1chunts Can you tell us where the script is that creates the readme files?

**Comment by ChrisArmit** [comment] 2020-08-14 09:16
Hi @pli888 

The filepath of the readme. sh script that we use is /tmp/readme.sh

Cheers
Chris A

**Comment by only1chunts** [comment] 2020-08-14 09:36
its on the parrot server (192.168.44.247) which is also where we run it (in the individual DOI folders).

The actual script looks like this (I removed jesse's password):

```

#!/bin/bash
# author:Jesse
pwd=$(pwd)
filename=$(basename $pwd)
wget -O "./$filename.xml" "http://gigadb.org/api/readme?doi=$filename&username=jesse@gigasciencejournal.com&password=********"
python /tmp/readxml.py ./$filename.xml ./readme_$filename.txt
rm -rf ./$filename.xml

```

**Comment by pli888** [comment] 2020-08-17 06:34
> `python /tmp/readxml.py ./$filename.xml ./readme_$filename.txt`

@only1chunts @ChrisArmit Your readme files are created by a Python program! Also, having these scripts stored in the `\tmp` directory isn't such a great idea as it's for temporary storage of files which the operating system or a sysadmin can delete at any time and no one would know about it.

**Comment by only1chunts** [comment] 2020-08-17 07:41
yes its a hack, but it does the job for now.
It has disappeared with no trace once, but we have a copy so we just replaced it. 
NB- There is another script that we use in the same place: md5sum.sh it just generates the md5 checksums for all files in the directory and its subdirectories.

**Comment by only1chunts** [comment] 2024-12-18 13:56
think this is not an issue anymore with the new createReadme script so closing this ticket.

**Closed by only1chunts** 2024-12-18 13:56 UTC
Labels: bug
