### ISSUE TITLE
Saving updates to File Attributes gives an Error (though change is saved). 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1857] opened 2024-05-14 11:16 UTC
**Describe the bug**
When I save a change made to a File Attribute, although the change is saved, I get the error 

> Error 500
> Class 'ReadFile' not found
> Go to the home page

**To Reproduce**
1. Go to https://gigadb.org/adminFile/update/id/544779
2. Scroll to the bottom of the page - BUSCO v5
3. Click 'Edit'
4. Make change and click 'save' (under Actions)
5. Click 'save' (bottom of page)
6. See error 

**Expected behavior**
1 to 5 as above
6. Return to Files Admin page (I think). 

**Screenshots**
![Screenshot 2024-05-14 at 12 09 00](https://github.com/gigascience/gigadb-website/assets/1359170/5ae955b2-3d30-44e7-8c44-0b93d26eafb2)
![Screenshot 2024-05-14 at 12 09 17](https://github.com/gigascience/gigadb-website/assets/1359170/12a61d82-c693-460e-8b8b-be3fe51cc522)

**Desktop (please complete the following information):**
 OS: Mac ventura 13.4
Browser: safari
Version 16.5

**Comment by alli83** [comment] 2024-07-30 08:13
I can't reproduce the error. Has the problem already been resolved?

**Comment by tuli** [comment] 2024-07-30 08:30
I am pretty sure this problem has indeed been resolved. I have done this sort of update many times since I issued this ticket and not had the same problem.
Thanks.

**Comment by rija** [comment] 2024-07-30 08:31
closing as not happening more

**Comment by alli83** [comment] 2024-07-30 08:32
@tuli thanks. I close this ticket then.

**Closed as completed by rija** 2024-07-30 08:31 UTC
Labels: bug, bug:Impact=low
