### ISSUE TITLE
updating project links via admin pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#375] opened 2020-01-08 11:54 UTC
**Describe the bug**
Given I try to update the details of an external project e.g. here http://gigadb.org/adminProject/update/id/35
When I click "Save" it gives error messages saying cannot have duplicates e.g.
![Screenshot_34](https://user-images.githubusercontent.com/6037145/71976076-5cbbda00-320d-11ea-8b71-2ccd85aa06ba.png)

The implication is that the system is trying to CREATE a new project entry instead of updating the existing one?!

**Expected behavior**
Given I am here http://gigadb.org/adminProject/update/id/35
Given I change the URL of the image location
When I click Save
It should save the changes to the database

**Comment by tuli** [comment] 2020-01-08 11:56
I found the same. I deleted the record and started again. Not a solution to the bug, but a way around it.

**Comment by kencho51** [comment] 2020-09-29 06:47
Hi @only1chunts and @tuli,
The `Duplicate` error means that the values of `Url` and `Name` have been existed in the database already, and `duplicate input` is not allowed by default. Please let us know if you want to allow `duplicate input` or not. And also be reminded that there will have some projects with the same `Url` or `name`  if  `duplicate input` is enabled.

**Comment by only1chunts** [comment] 2020-09-29 07:04
Hi @kencho51 ,
This is about updating existing projects, so no we do not want to allow duplicates, we want to be able to change an existing project.
perhaps the expected behaviour should read:
**Expected behavior**
Given I am here http://gigadb.org/adminProject/update/id/35
Given I change the URL of the image location
When I click Save (change this to "Update")
It should update the database entry to the new values given

**Comment by pli888** [comment] 2020-09-30 06:24
>When I click "Save" it gives error messages saying cannot have duplicates

It looks like the code in `function check_duplicate()` in the model Project class requires you to change both the `Url` and `Name` variables in order to update the project otherwise you see the `Duplicated URL` or `Duplicated Project Name` error. I think the problem is that it is returning the `project` currently undergoing an update by the user as the project with the duplicated URL or Project Name.

**Comment by alli83** [comment] 2024-09-03 06:34
https://github.com/gigascience/gigadb-website/pull/1924

**Comment by rija** [comment] 2024-09-13 08:34
closing as there is PR (#1924) for this

**Closed by rija** 2024-09-13 08:34 UTC
Labels: bug
