### ISSUE TITLE
[S569] Cut off live to beta database synchronisation from gigadb.org

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1191] opened 2023-01-11 08:06 UTC
## Prerequisites

* Handover of dataset spreadsheet upload tool has happened and curators are using the tool against the AWS deployment of the beta website.

## Plan

* [ ] 1. Shut down automated database synchronisation from CNGB GigaDB PostgreSQL database instance. 
* [ ] 2. Curators will run dataset spreadsheet tool *twice* on CNGB and AWS beta deployments for a while.
* [ ] 3. Manual curate/check both deployments to have confidence that AWS beta deployment has same results as CNGB deployment.
* [ ] 3. Turn off live CNGB deployment to avoid further changes
* [ ] 4. Final manual synchronisation from CNGB to RDS instances.
* [ ]  4.i make a manual backup of CNGB database
* [ ]  4.ii convert backup format to modern format
* [ ]  4.iii load the modern backup into Upstream live database
* [ ]  4.iv trigger a backup of current state of RDS on Upstream live
* [ ] 5. Curator team to stop using CNGB instance.

**Comment by rija** [comment] 2023-09-12 10:11
duplicate of #1414

**Closed as completed by rija** 2023-09-12 10:11 UTC
Labels: task:Size=8h
