### ISSUE TITLE
Running functional tests on a local Linux install of GigaDB

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#310] opened 2019-04-30 07:44 UTC
On a local installation of GigaDB on Linux (Ubuntu 18.04), there is a strange problem with running the functional tests.

[CommonDataProviders.php](https://github.com/gigascience/gigadb-website/blob/develop/protected/tests/support/CommonDataProviders.php) provides test data used by [SearchViewTest](https://github.com/gigascience/gigadb-website/blob/develop/protected/tests/functional/SearchViewTest.php) to test whether the search result page displays the formatted file size. The problem on Ubuntu 18.04 is that this functional test works fine when the array of arrays in the `adminFileExamplesOfAppropriateMetricDisplayOfFileSize()` function in [CommonDataProviders.php](https://github.com/gigascience/gigadb-website/blob/develop/protected/tests/support/CommonDataProviders.php) contains only 4 arrays:
```
public function provider() {
        return [
            'millet.chr.version2.3.fa.gz: 109B' => ["109", "B"],
            'Millet.fa.glean.cds.v3.gz: 13000B' => ["12.70", "KiB"],
            'Millet.fa.glean.pep.v3.gz: 85000000B' => ["81.06", "MiB"],
            'Millet.fa.glean.v3.gff: 14000000B' => ["13.35", "MiB"],
            //'Millet_scaffoldVersion2.3.fa.gz: 109000B' => ["106.45", "KiB"]
        ];
    }

# Run functional tests
$ docker-compose run --rm test ./tests/unit_functional
<snip>
pg_restore: creating ACL TABLE prefix
pg_restore: creating ACL TABLE sample_number
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.28 with Xdebug 2.7.1
Configuration: /var/www/protected/tests/phpunit.xml

....                                                                4 / 4 (100%)

Time: 339 ms, Memory: 14.00MB

OK (4 tests, 4 assertions)

</snip>
``` 
However, when there are 5 arrays in the `adminFileExamplesOfAppropriateMetricDisplayOfFileSize()` function in [CommonDataProviders.php](https://github.com/gigascience/gigadb-website/blob/develop/protected/tests/support/CommonDataProviders.php):
```
public function provider() {
        return [
            'millet.chr.version2.3.fa.gz: 109B' => ["109", "B"],
            'Millet.fa.glean.cds.v3.gz: 13000B' => ["12.70", "KiB"],
            'Millet.fa.glean.pep.v3.gz: 85000000B' => ["81.06", "MiB"],
            'Millet.fa.glean.v3.gff: 14000000B' => ["13.35", "MiB"],
            'Millet_scaffoldVersion2.3.fa.gz: 109000B' => ["106.45", "KiB"]
        ];
    }
```
This causes an error:
```
# Run functional tests
$ docker-compose run --rm test ./tests/unit_functional
<snip>
pg_restore: creating ACL TABLE prefix
pg_restore: creating ACL TABLE sample_number
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.28 with Xdebug 2.7.1
Configuration: /var/www/protected/tests/phpunit.xml

....F                                                               5 / 5 (100%)/var/www/protected/tests/support/BrowserPageSteps.php:39:
string(188) "<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"


Time: 348 ms, Memory: 14.00MB

There was 1 failure:

1) SearchViewTest::testItShouldDisplayFormattedFileSize with data set "Millet_scaffoldVersion2.3.fa.gz: 109000B" ('106.45', 'KiB')

Warning: include(PHP_Invoker.php): failed to open stream: No such file or directory in /var/www/vendor/yiisoft/yii/framework/YiiBase.php on line 463

Call Stack:
    0.0004     393168   1. {main}() /var/www/vendor/phpunit/phpunit/phpunit:0
    0.0242    5200824   2. PHPUnit_TextUI_Command::main() /var/www/vendor/phpunit/phpunit/phpunit:52
    0.0242    5200936   3. PHPUnit_TextUI_Command->run() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:116
    0.0419    8838664   4. PHPUnit_TextUI_TestRunner->doRun() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:186
    0.3480   11997728   5. PHPUnit_TextUI_ResultPrinter->printResult() /var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:523
    0.3480   11997728   6. PHPUnit_TextUI_ResultPrinter->printFailures() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:184
    0.3480   11997728   7. PHPUnit_TextUI_ResultPrinter->printDefects() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:285
    0.3480   11997728   8. PHPUnit_TextUI_ResultPrinter->printDefect() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:228
    0.3482   11997728   9. PHPUnit_TextUI_ResultPrinter->printDefectTrace() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:241
    0.3482   11997728  10. PHPUnit_Framework_ExpectationFailedException->__toString() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:265
    0.3489   12010672  11. PHPUnit_Util_Filter::getFilteredStacktrace() /var/www/vendor/phpunit/phpunit/src/Framework/Exception.php:65
    0.3491   12021792  12. PHPUnit_Util_Blacklist->isBlacklisted() /var/www/vendor/phpunit/phpunit/src/Util/Filter.php:67
    0.3491   12021792  13. PHPUnit_Util_Blacklist->initialize() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:70
    0.3492   12037392  14. class_exists() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87
    0.3492   12037432  15. spl_autoload_call() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87
    0.3493   12037472  16. YiiBase::autoload() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87

Warning: include(): Failed opening 'PHP_Invoker.php' for inclusion (include_path='/var/www/vendor/phpunit/php-invoker:/var/www/vendor/phpunit/phpunit-story:.:/usr/local/lib/php') in /var/www/vendor/yiisoft/yii/framework/YiiBase.php on line 463

Call Stack:
    0.0004     393168   1. {main}() /var/www/vendor/phpunit/phpunit/phpunit:0
    0.0242    5200824   2. PHPUnit_TextUI_Command::main() /var/www/vendor/phpunit/phpunit/phpunit:52
    0.0242    5200936   3. PHPUnit_TextUI_Command->run() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:116
    0.0419    8838664   4. PHPUnit_TextUI_TestRunner->doRun() /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:186
    0.3480   11997728   5. PHPUnit_TextUI_ResultPrinter->printResult() /var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:523
    0.3480   11997728   6. PHPUnit_TextUI_ResultPrinter->printFailures() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:184
    0.3480   11997728   7. PHPUnit_TextUI_ResultPrinter->printDefects() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:285
    0.3480   11997728   8. PHPUnit_TextUI_ResultPrinter->printDefect() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:228
    0.3482   11997728   9. PHPUnit_TextUI_ResultPrinter->printDefectTrace() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:241
    0.3482   11997728  10. PHPUnit_Framework_ExpectationFailedException->__toString() /var/www/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:265
    0.3489   12010672  11. PHPUnit_Util_Filter::getFilteredStacktrace() /var/www/vendor/phpunit/phpunit/src/Framework/Exception.php:65
    0.3491   12021792  12. PHPUnit_Util_Blacklist->isBlacklisted() /var/www/vendor/phpunit/phpunit/src/Util/Filter.php:67
    0.3491   12021792  13. PHPUnit_Util_Blacklist->initialize() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:70
    0.3492   12037392  14. class_exists() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87
    0.3492   12037432  15. spl_autoload_call() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87
    0.3493   12037472  16. YiiBase::autoload() /var/www/vendor/phpunit/phpunit/src/Util/Blacklist.php:87

Failed asserting that false is true.

/var/www/protected/tests/support/BrowserPageSteps.php:40
/var/www/protected/tests/functional/SearchViewTest.php:25
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:369
/var/www/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:318

FAILURES!
Tests: 5, Assertions: 5, Failures: 1.
</snip>
```

This problem seems to be related to that fact that there are 5 array items in the test data array. I have commented out any of the 5 arrays and the functional test passes. The error isn't specific to `Millet_scaffoldVersion2.3.fa.gz: 109000B`.

Strangely enough, the above error isn't seen on Mac installs of GigaDB.

**Comment by pli888** [comment] 2019-04-30 07:48
Another developer has a similar error on their Linux (Mint 19.1 and Docker 18.09.3) install of GigaDB:
[errors_vitaly.txt](https://github.com/gigascience/gigadb-website/files/3130312/errors_vitaly.txt)

**Comment by rija** [comment] 2019-05-02 07:13
Hi @pli888 

when looking  at the cause of the error from the output you've provided:

```
5 / 5 (100%)/var/www/protected/tests/support/BrowserPageSteps.php:39:
string(188) "<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

```
and knowing that nginx implementation of rate limit returns that error when over the limit:
https://www.nginx.com/blog/rate-limiting-nginx/

and that Gigadb has rate limit configured for the /search endpoint:
https://github.com/gigascience/gigadb-website/blob/develop/ops/configuration/nginx-conf/sites/gigadb.dev.http.conf

seem to indicate that local containerised nginx thinks it is being  DOS-ed by the functional tests.
Why it affects Linux and not Macs is probably connected to the fact that Docker on Linux is directly using the host's kernel while on the mac, Docker uses a Linux  layer over macOS.

Because in gigadb, nginx site config are environment dependent, one possible fix is increase burst rate for the dev environment (at the moment it's set to 3) to a big number:

```
location /search {
        limit_req zone=gigadbsearch burst=50 nodelay;
``` 

Let me know if that works for you.

**Comment by pli888** [comment] 2019-05-03 05:50
>Let me know if that works for you.
```
location /search {
        limit_req zone=gigadbsearch burst=50 nodelay;
```

@rija this works for me on Ubuntu and Mint.

**Closed** 2020-08-03 14:44 UTC
Labels: bug
