### ISSUE TITLE
Manuscript links not displayed 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#611] opened 2021-04-27 14:18 UTC
## User story

>As a user  
>I want to see if there are any peer-reviewed publication(s) associated with GigaDB datasets
>So that I can choose to read them (or not). 

## Acceptance criteria

>Given I am looking at a GigaDB record
>Which has an associated peer-reviewed publication in either GigaScience or GigaByte
>Then I want to see the publication(s) and be able to navigate to them.

## Additional Info

Related to work in #242 (which has been closed)
Example: http://dx.doi.org/10.5524/100500 
'Read the peer-reviewed publication(s):' (under Additional details), should link to https://doi.org/10.1093/gigascience/giy116
nb I am not sure of exactly how the citation should appear (because there are none to compare to!).

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by rija** [comment] 2021-05-07 08:43
Duplicate of #512

**Comment by only1chunts** [comment] 2021-05-28 15:45
@rija can we add a link somewhere here to the work that is being done that will fix this problem? I keep coming back to it because it's a very noticeable issue on the website. I don't know if it's something that is being fixed in this sprint or not? or what size=0 means?

**Comment by rija** [comment] 2022-01-07 08:19
closing as It's working on staging.gigadb.org

**Closed by rija** 2022-01-07 08:19 UTC
Labels: backlog:Story, backlog:Size=0
