### ISSUE TITLE
Update BioMed Central to OUP 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#141] opened 2017-12-07 09:27 UTC
Page http://gigadb.org/site/about still says BioMed Central instead of OUP!

Change to OUP on public website, the CNGB mirror and the github repo.

**Comment by only1chunts** [comment] 2017-12-07 09:31
ticket not required as its a duplicate of #140 , thanks.

**Closed by only1chunts** 2017-12-07 09:31 UTC
